### ISSUE TITLE
How to get friend list?

### ISSUE THREAD

**Issue by D00msDay** [code-disaster/steamworks4j#10]
How to get friends list in steamworks4j?

**Comment by titoasty** [comment]
I'm not sure you can, you should write the code yourself and add a pull request

**Comment by code-disaster** [comment]
I've added friend list enumeration and persona state queries while testing the peer2peer functions, currently still in a separate branch (serverapi-merge). I'll probably merge them to master this weekend.

**Comment by D00msDay** [comment]
Thank you so much
