### ISSUE TITLE
should we make every functions in the Callback interfaces have a default empty method?

### ISSUE THREAD

**Issue by XenoAmess** [code-disaster/steamworks4j#110]
As the current code cause adding a function into a Callback interface will make every user must change codes.

Thus might cause dependency hell.

**Comment by XenoAmess** [comment]
example : https://github.com/cyanpotion/cyan_potion/runs/5523216193?check_suite_focus=true

**Comment by XenoAmess** [comment]
If you are interested I can make the pr for you.

**Comment by code-disaster** [comment]
I've seen _some_ advantage in breaking user code (so that you are aware that there's been changes in the interface after a version update), but I see your point. Had to tell the Maven project to upgrade from Java 7 to Java 8 though. 😱
