### ISSUE TITLE
SetGameLauncherMode

### ISSUE THREAD

**Issue by Trekopep** [code-disaster/steamworks4j#120]
If possible, would like [ISteamUtils SetGameLauncherMode](https://partner.steamgames.com/doc/api/isteamutils#SetGameLauncherMode) to be implemented. 
From the documentation:

> In game launchers that don't have controller support you can call this to have Steam Input translate the controller input into mouse/kb to navigate the launcher

For our use case, we have an in-game editor that isn't controller compatible. We're trying to get our game Steam Deck verified, and Valve recommended using that when the player opens the in-game editor.

Thanks!

**Comment by Trekopep** [comment]
@code-disaster Speedy, thanks!

I see the steamworks4j64.dll was updated, but it looks like it still doesn't include the method? When I try to call it, I get a java.lang.UnsatisfiedLinkError.
![image](https://user-images.githubusercontent.com/27928766/193339891-9020c904-2bdb-42a5-b1c8-387b0cc6181d.png)

**Comment by code-disaster** [comment]
I messed up the deployment - the native libraries did not include those changes. Should work now with the latest commit.
