### ISSUE TITLE
Should Update de Steam SDK?

### ISSUE THREAD

**Issue by sebaber** [code-disaster/steamworks4j#125]
Hi!

Today i receive an email from `steampublish@valvesoftware.com` that advice us to update the Steam SDK if the game use [ISteamUser::GetAuthSessionTicket](https://partner.steamgames.com/doc/api/ISteamUser#GetAuthSessionTicket)(), that i think is the case because we use `public SteamAuthTicket getAuthSessionTicket(ByteBuffer authTicket, int[] sizeInBytes) throws SteamException` in some cases.

If this is the case, we can give a hand to colaborate to this migrations if it is neccesary.

Thanks for the time and for this awesome Wrapper for JAVA of Steam SDK!

**Comment by code-disaster** [comment]
f69b809 adds `getAuthTicketForWebApi()`, if this is what you are asking about.

**Comment by sebaber** [comment]
Yeah that is what im looking for! Thanks a lot for the fast response! Appreciate a lot!

**Comment by sebaber** [comment]
I could found the new method in the SNAPSHOT, but idk if im using well, because i could not found a way to get the ticket that should give me for the user to authenticate. There is something else that i am missing?

**Comment by code-disaster** [comment]
It is returned in the new callback. See https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamClientAPITest.java#L43.

Note that you need to copy the data, the byte[] array will point to invalid memory after the callback returns.

**Comment by Zomis** [comment]
@code-disaster I don't know if I'm doing anything wrong, trying to copy the old library loader and use it (see #127), but I'm not getting the `onGetTicketForWebApi` callback.

I just get an integer (incrementing from 1 or 2 or something) in response to `SteamUser.getAuthTicketForWebApi()`, but the callback is never triggered? (And yes, I am running `SteamAPI.runCallbacks()`)

**Comment by code-disaster** [comment]
Not sure about that, but is it possible that you have some old version of the steamworks4j DLL lingering and getting picked up by the library loader somewhere?

**Comment by sebaber** [comment]
> It is returned in the new callback. See https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamClientAPITest.java#L43.
> 
> Note that you need to copy the data, the byte[] array will point to invalid memory after the callback returns.

Yeah that was i am looking for! It has to be asyncronic i did not realize that. TSM for the help! i will close this issue.

**Comment by Frotty** [comment]
@sebaber How did you get this to work? In my case the callback is not triggered (#143)
