### ISSUE TITLE
Missing GetAuthTicketForWebApi

### ISSUE THREAD

**Issue by Zomis** [code-disaster/steamworks4j#126]
When reading here: https://partner.steamgames.com/doc/features/auth#client_to_backend_webapi

It says:

> The client must retrieve a session ticket by calling [ISteamUser::GetAuthTicketForWebApi](https://partner.steamgames.com/doc/api/ISteamUser#GetAuthTicketForWebApi).
To guarantee a valid ticket, the client must wait for the [ISteamUser::GetTicketForWebApiResponse_t](https://partner.steamgames.com/doc/api/ISteamUser#GetTicketForWebApiResponse_t) callback.

But these methods does not seem to be implemented in steamworks4j

**Comment by code-disaster** [comment]
Added in f69b809

**Comment by Frotty** [comment]
@Zomis Did you get the call to work? I am having trouble getting the ticket data (https://github.com/code-disaster/steamworks4j/issues/143)
