### ISSUE TITLE
Beta tag of next release?

### ISSUE THREAD

**Issue by tomcashman** [code-disaster/steamworks4j#13]
I was wondering if you could release a beta tag (or final if you think it's stable) for the current snapshot? Was hoping to use the new simpler API in my game.

Btw, love the library, you should try get it stickied on the Steam Developer Group as I had started coding my own JNI wrapper before I discovered this.

**Comment by code-disaster** [comment]
I've released version 1.1.0 on Maven Central a few minutes ago.

**Comment by tomcashman** [comment]
Woo! Thanks! :)
