### ISSUE TITLE
Failed to initialize

### ISSUE THREAD

**Issue by TarVK** [code-disaster/steamworks4j#137]
Hi there, 

My game kept failing to initialize despite taking all the steps described in the get started documentation. I was using the app ID `1456390`, which I previously used in a unity game. This is a special test ID which should allow you to test your prototype including controller support without requiring to make an app id on steam yourself, see this thread:  https://github.com/rlabrecque/Steamworks.NET/issues/380#issuecomment-1490588180. 

This worked fine in unity until yesterday, and today I tried setting up steamworks4j in another project for the first time, and it kept failing to initialize. Eventually I went back to unity to see what I did differently there, and found out it stopped working there too. Turns out that just before I started testing steamworks4j, something happened to this app id, and it no longer works. I tried using a random app id from another game I own, and it worked.

This is not a problem with steamworks4j, so this issue can be closed, but I just literally spent 6 hours debugging this because it was my first experience with steamworks4j and I want to save other people the pain of figuring this out themselves.

**Comment by code-disaster** [comment]
For future reference, app ID 480 is the ID of Steam's "SpaceWar" sample project. You can always start testing with this one.
