### ISSUE TITLE
how to get username/user details from steamID ?

### ISSUE THREAD

**Issue by titoasty** [code-disaster/steamworks4j#15]
How to get a username / user details from a SteamID ?
There is "requestUserInformation" in SteamFriends, but for what I understand, the callback may be "onPersonaStateChange", but it only returns persona state and steam ID.
Is it incomplete or is there another way ?

**Comment by code-disaster** [comment]
- If requestUserInformation() returns false, you can call getFriendPersonaState()/getFriendPersonaName()/get*FriendAvatar() immediately. If it returns true, you need to wait for onPersonaStateChange() callbacks.
- On receiving onPersonaStateChange(), you can query state & avatars based on the value of the PersonaChange enum. I suppose. I never tried that myself, was only testing with friend info my Steam client has already cached. So e.g. if the value is PersonaChange.Avatar, it means the avatar images are done downloading and can be queried.

**Comment by titoasty** [comment]
Ok I have to test with "non" friends steam ids

**Comment by code-disaster** [comment]
"Space Grunts" uses this for leaderboards, so I consider it working. ;)

**Comment by Frotty** [comment]
`getFriendPersonaName` only works for friends. Does the callback work for non-friends as well?
