### ISSUE TITLE
Cannot get any stats / achievements.

### ISSUE THREAD

**Issue by wessles** [code-disaster/steamworks4j#16]
First off, thanks for making this wrapper, it's awesome. I am having an issue with connecting to steam's servers. I am using some code from your example programs.

Log (ignore X's):

```
Register user ...
Setting breakpad minidump AppID = 392020
Steam_SetMinidumpSteamID:  Caching Steam ID:  XXXXXXXXXXXXXXXXX [API loaded no]
Register user stats callback ...
Register remote storage ...
Register UGC ...
Register Utils ...
Local user account ID: XXXXXXXXX
App ID: 392020
requestCurrentStats: true 
User stats received: gameId=392020, userId=XXXXXXXXX, result=Fail
Num of achievements: 0

Process finished with exit code 255
```

The program goes like this:
* I set all my callbacks for the user, user stats, remote storage, etc.
* Then I call requestCurrentStats (which returns true).
* But the retrieval callback says that it failed: `result=Fail`.
* If I try to use the data, it gives me no achievements, even though I set up 7 of them.

I cannot access any stats or achievements, which are *vital* to me releasing my game on schedule. What is going on here? Could it have something to do with Steamworks4j being out of date with Steam's API (1.33 vs. 1.34)?

I'm on Ubuntu 14.04 x86_64 with OpenJDK 7, running Intellij IDEA with libGDX, if it matters.

Thanks,
-wes

**Comment by wessles** [comment]
Never-mind any of this.

Apparently, pressing "save" on achievements / stats isn't enough for steamworks. Apparently, you also have to 'publish' it for the changes to take effect. Maybe naming it 'commit' or 'update' would have been less.. time-wasting.

Keep up the good work on this library!

**Comment by code-disaster** [comment]
Glad you found the issue - yeah the Steamworks configuration pages can be a little... irritating at times. :)

**Comment by wessles** [comment]
Glad I solved it before I posted this question elsewhere :P.
