### ISSUE TITLE
Cannot compile into a jar file

### ISSUE THREAD

**Issue by MightyElemental** [code-disaster/steamworks4j#19]
I followed the instructions on how to compile the code (http://code-disaster.github.io/steamworks4j/build-instructions.html). But it did not work. The instructions are not very easy to follow. Please could you simplify the steps or just add a .jar file to the github repo. Thanks.

**Comment by code-disaster** [comment]
As I wrote in the instructions, you don't need to compile native code if you don't want to *modify* native code. Just run ```mvn package``` in the root directory. Grab ```steamworks4j-x.x.x-SNAPSHOT.jar``` from the ./java-wrapper/target folder.

I do not plan to upload any .jar files. If required, you can fetch release .jars from http://mvnrepository.com/artifact/com.code-disaster.steamworks4j/steamworks4j, though I recommend using a suitable build system, e.g. Maven or Gradle, anyway.

**Comment by MightyElemental** [comment]
I don't know how I would even use Maven or Gradle to compile the code, but
thanks for a link. BTW what is the difference between me compiling it and
you distributing a pre-compiled copy? Is it just that if I compile it, it
will be the latest version? Anyway thanks again for the link

On Sun, Oct 11, 2015 at 8:45 PM, Daniel Ludwig <notifications@github.com>
wrote:

> As I wrote in the instructions, you don't need to compile native code if
> you don't want to *modify* native code. Just run mvn package in the root
> directory. Grab steamworks4j-x.x.x-SNAPSHOT.jar from the
> ./java-wrapper/target folder.
>
> I do not plan to upload any .jar files. If required, you can fetch release
> .jars from
> http://mvnrepository.com/artifact/com.code-disaster.steamworks4j/steamworks4j,
> though I recommend using a suitable build system, e.g. Maven or Gradle,
> anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-disaster/steamworks4j/issues/19#issuecomment-147238988>
> .
>



-- 

YouTube: 720mine <http://www.youtube.com/user/720mine>
Rocket Raiser: Minegeek360 <https://rocketraiser.com/u/minegeek360/>
James Burnell

**Comment by code-disaster** [comment]
> what is the difference between me compiling it and you distributing a pre-compiled copy? Is it just that if I compile it, it will be the latest version?

Yes, exactly.
