### ISSUE TITLE
SteamMatching getLobbyMemberByIndex returns bad SteamID

### ISSUE THREAD

**Issue by ndm250** [code-disaster/steamworks4j#23]
Calling  `getAccountID` returns zero from `getLobbyMemberByIndex` for all calls and similar error for `getLobbyOwner`.

Tested with dozens of different lobbies and application runs. Added the following snippet to the SteamMatchmakingTestApp with same results.
````
@Override
public void onLobbyMatchList(int lobbiesMatching) {
    System.out.println("Found " + lobbiesMatching + " matching lobbies.");

    lobbies.clear();
    for (int i = 0; i < lobbiesMatching; i++) {
        SteamID lobby = matchmaking.getLobbyByIndex(i);
        lobbies.put(lobby.getNativeHandle(), lobby);

        int memberCount = matchmaking.getNumLobbyMembers(lobby);
        for(int m = 0; m < memberCount; m++) {
            SteamID member = matchmaking.getLobbyMemberByIndex(lobby, m);
            System.out.println("ACCOUNT ID: " + member.getAccountID()); // ACCOUNT ID: 0
        }
    }
}
````
Any ideas?

**Comment by code-disaster** [comment]
According to the Steam headers this data is "only accessible if the lobby user is a member of the specified lobby". So you have to join it first before querying other lobby members.

**Comment by ndm250** [comment]
Okay. Thanks,
