### ISSUE TITLE
Crash when using bundled 64-bit bundled JRE on Windows

### ISSUE THREAD

**Issue by Osaris31** [code-disaster/steamworks4j#24]
Hi,

First I'd like to thank you very much for the awesome work.
Here is the issue I'm facing: everything works well when I launch from Eclipse, with a 64-bit JVM.
Everything works well when I launch from a 32-bit packr exe, with a 32-bit JVM.
But it crash when I launch from a 64-bit packr exe, with a 64-bit JVM.

I tried several JVM (OpenJDK 7, Java SE 8) and it crashed exactly the same:

> A fatal error has been detected by the Java Runtime Environment:
>
>  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff98f3b6996, pid=8980, tid=12792
>
> JRE version: OpenJDK Runtime Environment (7.0-b31) (build 1.7.0-u45-unofficial-b31)
> Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode windows-amd64 compressed oops)
> Problematic frame:
> C  [steamworks4j64.dll+0x6996]

> A fatal error has been detected by the Java Runtime Environment:
>
>  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9930e6996, pid=704, tid=5368
>
> JRE version: Java(TM) SE Runtime Environment (8.0_71-b15) (build 1.8.0_71-b15)
> Java VM: Java HotSpot(TM) 64-Bit Server VM (25.71-b15 mixed mode windows-amd64 compressed ops)
> Problematic frame:
> C  [steamworks4j64.dll+0x6996]

The game start well, init() is done without problem, but it crash when I use getPersonaName to retrieve the full username of the player (which works well in 32-bit).

>Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
>j  com.codedisaster.steamworks.SteamFriends.getPersonaName(J)Ljava/lang/String;+0
>j  com.codedisaster.steamworks.SteamFriends.getPersonaName()Ljava/lang/String;+4
>j  net.osaris.alchemist.multiplayer.User.checkAuth()Z+34
>j  net.osaris.alchemist.j.i.<init>()V+63
>j  net.osaris.alchemist.j.i.a()V+4
>j  net.osaris.alchemist.j.<init>()V+140
>j  net.osaris.alchemist.a.g()V+117
>j  net.osaris.alchemist.a.render()V+636
>j  com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()V+684
>j  com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run()V+27
>v  ~StubRoutines::call_stub

Here is the full crash file: http://pastebin.com/tLmcqKNu

Let me know if you need more info.

Thanks!

**Comment by code-disaster** [comment]
Very strange. There isn't much to this function which can go wrong. Is that with the latest version version of packr? And, do following calls to Steam work if you skip this one getPersonaName() call, or do they crash too?

**Comment by Osaris31** [comment]
I tried that, it crashes on the following call:

C  [steamworks4j64.dll+0x6920]
j  com.codedisaster.steamworks.SteamFriends.getFriendCount(Lcom/codedisaster/steamworks/SteamFriends$FriendFlags;)I+8

**Comment by Osaris31** [comment]
Tried to make a minimal test case:

```java
	public static void main (String[] arg) {
		
		if (!SteamAPI.init()) {
			System.out.println("No Steam logon.");
		}
		else {
			SteamUserCallback callback = new UserCallback();
			user = new SteamUser(callback);
			friends = new SteamFriends(friendsCallback);
			if (SteamAPI.isSteamRunning()) {
				SteamAPI.runCallbacks();
			}

			System.out.println(friends.getPersonaName());
		}
	}
```
Crash with following hs_err:
[hs_err_pid5744.txt](https://github.com/code-disaster/steamworks4j/files/103062/hs_err_pid5744.txt)

**Comment by code-disaster** [comment]
I think I found the problem. It'd be cool if you can verify the fix before I push a new build to Maven Central.

**Comment by Osaris31** [comment]
That's great, could you please send me the updated jar or a link to it, here or at pocketnew@gmail.com and I'll test it right away.
Thanks

**Comment by code-disaster** [comment]
[steamworks4j-1.2.3-SNAPSHOT.zip](https://github.com/code-disaster/steamworks4j/files/104136/steamworks4j-1.2.3-SNAPSHOT.zip)

**Comment by Osaris31** [comment]
It works, everything is fine now!
Thanks.
