### ISSUE TITLE
getAuthSessionTicket not filling buffer

### ISSUE THREAD

**Issue by bgirard** [code-disaster/steamworks4j#25]
```
ByteBuffer authTicket = ByteBuffer.allocate(2048);
int authSessionTicket = steamUser.getAuthSessionTicket(authTicket);
byte[] array = authTicket.array();
```
I'm getting back a zero array. I don't see how to register ValidateAuthTicketResponse_t. I've tried waiting for 10s of second before checking the buffer but even then it's not filled.

**Comment by code-disaster** [comment]
Please try with using ByteBuffer.allocateDirect().

**Comment by code-disaster** [comment]
Note: I conducted some tests and made the Java API a little more robust. Have a look at the latest changes at https://github.com/code-disaster/steamworks4j/commits/master.

**Comment by bgirard** [comment]
allocateDirect() fixed my problem. The new API looks a lot better, I'll update to it when I get the chance.

BTW This is my title if you want to add it to the showcase:
http://steamcommunity.com/sharedfiles/filedetails/?id=426570756

I'm just using SteamUser/SteamUtils for now, the rest is all server-side using the WebAPI.
