### ISSUE TITLE
Request: ability to add more than one preview image to published files

### ISSUE THREAD

**Issue by Zarkonnen** [code-disaster/steamworks4j#27]
In my particular case, I'm uploading ship designs that really need both an exterior and an interior view for people to see. Being able to specify multiple preview images would be very useful for this.

**Comment by code-disaster** [comment]
Aside from the issue that I didn't implement the *more recent* additions to ISteamUGC yet, is there even an option to add more than one preview image? I see a function to "retrieve additional preview URLs", but none to set them.

**Comment by Zarkonnen** [comment]
Ah, if there's no way to do it, then there's no way to do it. I can probably work around it somehow.
