### ISSUE TITLE
SteamID(long id) should be public (or expose an equivilent API)

### ISSUE THREAD

**Issue by bgirard** [code-disaster/steamworks4j#28]
The current API doesn't work well across the network. SteamID is not serializable, nor would I really want to be forced to send SteamID structure across the network and persist then with the account save files and require steamworks4j deserilization to open my save files. Luckily getNativeHandle() is exposed although deprecrated. Using the steamid handle is better since steam can't easily change it so it's not an implementation detail that's likely to break.

On the server side receiving/storing a raw steamid handle is ideal. However I can't create a SteamID to call 'steamGameServerStats.setUserAchievement(steamIDHandle, key);' because SteamID(long) is private.

I understand that hiding the steamid handle is better for single player game but I think there needs to be a solution for multi player games. Either SteamID(long) could be made public or perhaps some more explicit SteamID.createFromRemoteHandle(long) function to stear single player games to avoid this.

**Comment by code-disaster** [comment]
Thanks for the feedback. I've added static functions to create a steamID by value:
https://github.com/code-disaster/steamworks4j/blob/master/java-wrapper/src/main/java/com/codedisaster/steamworks/SteamID.java#L37
