### ISSUE TITLE
Version 1.2.4 is not available in Maven repository 

### ISSUE THREAD

**Issue by ndm250** [code-disaster/steamworks4j#32]
Change log describes a version 1.2.4 that I am unable to download from Maven.

`		<dependency>
		  <groupId>com.code-disaster.steamworks4j</groupId>
		  <artifactId>steamworks4j</artifactId>
		  <version>1.2.4</version>
		</dependency>`

> Could not find artifact com.code-disaster.steamworks4j:steamworks4j:jar:1.2.4 in central (http://repo.maven.apache.org/maven2)

Version 1.2.3 does work however.

**Comment by code-disaster** [comment]
There is no release after v1.2.3 yet. Usually, the top-most section in CHANGES lists the last modifications done in the master branch.

**Comment by ndm250** [comment]
Oh ok. There has been quite a bit of changes since v1.2.3, one of which I'd like to take advantage of. Is there anything holding back a release? It's been almost a month since the last commit. Do you have a TODO list before you release v1.2.4 - anything I can help with?

**Comment by code-disaster** [comment]
> Is there anything holding back a release?

Just some outstanding tests of recent changes, and doing the release itself. Which I did just now.
