### ISSUE TITLE
Steam Inventory?

### ISSUE THREAD

**Issue by kevinmurphy678** [code-disaster/steamworks4j#33]
Does the wrapper have any access to steam inventory yet? I was thinking of using it but I haven't read anything about it or know how it works. How would you go about securing items in a game and tying them to steam accounts inventory? If you have any idea please let me know.

What would stop a player from just adding the items themselves if they have access the client jar.

**Comment by code-disaster** [comment]
The Steam Inventory Service is a rather new API which doesn't have a Java wrapper yet.

The Steamworks documentation has more details about how inventory items are distributed. tl&dr: as the game client can't be trusted, the API doesn't allow clients to say "hey, I want item X".

**Comment by Indieveloper** [comment]
Will this be added in the future?

**Comment by code-disaster** [comment]
I recently watched the [Steam Dev Days talk](https://www.youtube.com/watch?v=jDfhPTSOLis), and the whole topic / a proper implementation of Steam Inventory seems  far from trivial. I wonder if there's a real demand for steamworks4j users.

Until now I would have assessed this interface as "nice to have" for the common user of this wrapper. Do you actually plan to add Steam Inventory support for your game?

**Comment by kevinmurphy678** [comment]
I don't plan on it any more

**Comment by D3add3d** [comment]
I do :)

**Comment by Zweistein2** [comment]
I would like to use the steam inventory stuff, too

**Comment by tylerhasman** [comment]
I would also like steam inventory support!

**Comment by kevinmurphy678** [comment]
Well I think I could use this now.
