### ISSUE TITLE
MicroTxnAuthorizationResponse_t callback

### ISSUE THREAD

**Issue by Aperico-com** [code-disaster/steamworks4j#37]
Does this lib support the use of the MicroTxnAuthorizationResponse_t used for in-game shops? I could not find it when I looked through the JNI natives folder but I was hoping I might have missed it. If it is not supported do you have any plans to add it?

**Comment by code-disaster** [comment]
It's not implemented in the wrapper yet. Is there anything else you are aware of, WebAPI calls aside, which would be required for integrating in-game purchases?

**Comment by Aperico-com** [comment]
I believe that is it. Except the calls you make with the WebAPI it uses 
SteamAPI_Init()
SteamUser()->GetSteamID()
SteamApps()->GetCurrentGameLanguage()
Which are already implemented

Then after a certain WebAPI call is made you need to listen on the callback
MicroTxnAuthorizationResponse_t

**Comment by Aperico-com** [comment]
It works perfectly, big thank you!
