### ISSUE TITLE
SteamController interface can't find controllers

### ISSUE THREAD

**Issue by Ezard** [code-disaster/steamworks4j#39]
The following code (which seems to be correct, based on Valve's sparse documentation and having looked at SpaceWar) returns an array of null values

	try {
		SteamAPI.init();
	} catch (SteamException e) {
		e.printStackTrace();
	}

	SteamController controller = new SteamController();
	controller.init();

	SteamControllerHandle[] handles = new SteamControllerHandle[STEAM_CONTROLLER_MAX_COUNT];
	controller.getConnectedControllers(handles);

My controller is definitely connected, as I can use it in SpaceWar, 3rd party games, and Windows itself

Both of the init methods return true

EDIT: The SteamControllerTestApp that you provide also doesn't detect any controllers, so I'm assuming it's a problem on my end?

**Comment by code-disaster** [comment]
Hi,

hard to tell what's going wrong, but here are some ideas:

- make sure you run your Steam client with "-forcecontrollerappid <your-app-id>"
- check if the controller profile you have to setup according to the Steamworks docs is showing up in big picture mode
- run SteamAPI.runCallbacks() and/or controller.runFrame() each frame
- make sure the controller is actually turned on when you call getConnectedControllers(), during my first tests I found mine going back to sleep mode pretty fast

**Comment by Ezard** [comment]
Seems I just needed to run SteamAPI.runCallbacks() or controller.runFrame() before searching for connected controllers - thanks for the info!
