### ISSUE TITLE
SteamFriendsCallback doesn't exist in 1.0.1

### ISSUE THREAD

**Issue by AwesomeSpider** [code-disaster/steamworks4j#4]
I installed steamworks4j 1.0.1 using gradle and my IDE (IntelliJ IDEA) says that SteamFriendsCallback doesn't exist. Your example code contains reference to this class and I searched in your repository and it's there. I don't know what going on. I will try refreshing gradle, but if this doesn't succeed it is probably something wrong in your code.

**Comment by AwesomeSpider** [comment]
Nope, refreshing didn't work.

**Comment by AwesomeSpider** [comment]
On doing more research I have found that it isn't installing properly. The full code isn't there. What should I do?

**Comment by code-disaster** [comment]
SteamFriendsCallback was added after 1.0.1 and not released on Maven Central yet. I've just done that a few minutes ago, so 1.0.2 should be available now.

**Comment by AwesomeSpider** [comment]
Oh, thank you!
