### ISSUE TITLE
SteamUGCCallback onRequestUGCDetails() not being called

### ISSUE THREAD

**Issue by grizeldi** [code-disaster/steamworks4j#41]
When I request UGC details as followed
```
SteamPublishedFileID [] ids = new SteamPublishedFileID[steamUGC.getNumSubscribedItems()];
steamUGC.getSubscribedItems(ids);
steamUGC.sendQueryUGCRequest(steamUGC.createQueryUGCDetailsRequest(Arrays.asList(ids)));
```
In my callback method onUGCQueryCompleted() gets called instead of onRequestUGCDetails(). I currently manually call onRequestUGCDetails() from onUGCQueryCompleted(), but I think this is not the intended behavior.

**Comment by code-disaster** [comment]
The onRequestUGCDetails() callback is triggered by requestUGCDetails(), which is deprecated according to the Steamworks documentation.

The onUGCQueryCompleted() callback is triggered by sendQueryUGCRequest(). In the callback, you are supposed to use getQueryUGCResult() to get the details of each result item. See https://github.com/code-disaster/steamworks4j/blob/master/java-wrapper/src/test/java/com/codedisaster/steamworks/test/SteamClientAPITestApp.java#L222-L228 for an example.

**Comment by grizeldi** [comment]
I see. The steamworks' docs aren't always the most explanatory, at least to me.
Thanks for the info, what you explained up there is actually exactly what I'm doing atm.

**Comment by code-disaster** [comment]
> The steamworks' docs aren't always the most explanatory

Yes. That's quite an understatement. :)
