### ISSUE TITLE
[Feature request] SteamNetworking getP2PSessionState() missing

### ISSUE THREAD

**Issue by grizeldi** [code-disaster/steamworks4j#43]
Without this method it is impossible to tell if you are connected to the remote end or not, so it's kinda very required to do any actual work.

**Comment by code-disaster** [comment]
> Without this method it is impossible to tell if you are connected to the remote end or not

Just a small note: the Steamworks header seems to disagree with you, as it says `// should only (be) needed for debugging purposes`.

**Comment by grizeldi** [comment]
Why is this still open?
