### ISSUE TITLE
Open web page INSIDE Steam Client?

### ISSUE THREAD

**Issue by lsliwko** [code-disaster/steamworks4j#44]
Hello,

How to open a web page INSIDE Steam Client?
Is that possible?

Les

**Comment by code-disaster** [comment]
I suppose it's `SteamFriends.activateGameOverlayToWebPage()` what you are looking for.

**Comment by lsliwko** [comment]
Thanks man!

Also, is there any API to get either version of compiled Steam SDK library or version of steamworks4j library?

something like SteamAPI.getLibraryVersion()?

**Comment by code-disaster** [comment]
No. The SDK doesn't have an API for that, and I didn't bother to add one for the Java API. What do you want to use it for, if I may ask?
