### ISSUE TITLE
[Feature Request] Support for Steam Encrypted App Ticket

### ISSUE THREAD

**Issue by ClundXIII** [code-disaster/steamworks4j#45]
Hi,

is it possible to implement the encrypted app ticket functionality? It does not require any connection to a running steam client and basically works "offline".

**Comment by code-disaster** [comment]
Hi,

sure its possible, though it probably would require to ship the additional set of runtime libraries within the JAR files (if I don't want the user to handle that manually).

> It does not require any connection to a running steam client and basically works "offline".

Are you sure about that? The client-side encryption is triggered through ISteamUser:: RequestEncryptedAppTicket(), and I don't think this works w/o a running Steam client.

**Comment by ClundXIII** [comment]
Yes. I am sure about this. The whole reason this exists is that you can have a master server with a secret key to verify the tickets for you without any running steam instance.
see: https://partner.steamgames.com/documentation/auth
Under "Encrypted App ticket".

Since the web API is somehow mentioned as deprecated and a non gui server with a running steam account in the background sounding awful this seems to be the only way to authenticate a user ticket.
(Correct me if I am wrong)

**Comment by ClundXIII** [comment]
"Are you sure about that? The client-side encryption is triggered through ISteamUser:: RequestEncryptedAppTicket(), and I don't think this works w/o a running Steam client."

Yes. But the server side can decrypt it without having a running steam client afaik.

**Comment by code-disaster** [comment]
FYI I started working on this. It's not as trivial as you may think, because the server-side encryption library isn't meant to be redistributed. My current approach is to add a **steamworks4j-server** module which will contain the server-side EncryptedAppTicket API, and can be added as an additional dependency to a game server project.

**Comment by ClundXIII** [comment]
Thank you!

You can also add IronArmada to the showcase list if you want:

http://store.steampowered.com/app/581910/Iron_Armada/
http://www.ironarmada.net/
(the website is currently down or something, should be fixed soon.)

**Comment by code-disaster** [comment]
There now is a `steamworks4j-server` module which contains the EncryptedAppTicket functions. Just pull the latest version and run `mvn package`, which creates a JAR at `./server/target/`. 

By default, Maven now pulls all required native libraries from the Steamworks SDK folder, so you'll need to put a copy to `./sdk/` (like described [here](http://code-disaster.github.io/steamworks4j/build-instructions.html)).

There's also a test application. I briefly tested with the app ID and private key for the SpaceWar! sample.

**Comment by ClundXIII** [comment]
Thanks! I got it working. But I have a bugfix for you, the version for tests is wrong:

diff --git a/tests/pom.xml b/tests/pom.xml
index f70ab4d..95a1f50 100644
--- a/tests/pom.xml
+++ b/tests/pom.xml
@@ -30,7 +30,7 @@
                <dependency>
                        <groupId>com.code-disaster.steamworks4j</groupId>
                        <artifactId>steamworks4j-server</artifactId>
-                       <version>1.6.3-SNAPSHOT</version>
+                       <version>1.7.0-SNAPSHOT</version>
                </dependency>
        </dependencies>

**Comment by robinhood128** [comment]
Hello, I like everything about this project so far.
But it would be usefull for me if I could download the server jar from somewhere.
I don't really know how maven works, a jar would be appreciated

**Comment by code-disaster** [comment]
I strongly recommend to get familiar with Maven. It'll make your life in the Java world a lot easier.

I uploaded a first snapshot version: [client](https://oss.sonatype.org/content/repositories/snapshots/com/code-disaster/steamworks4j/steamworks4j/1.7.0-SNAPSHOT/), [server](https://oss.sonatype.org/content/repositories/snapshots/com/code-disaster/steamworks4j/steamworks4j-server/1.7.0-SNAPSHOT/)

I do not include the **encryptedappticket** shared libraries, because they are not part of the redistributable package. This means the loader won't find them by only adding the JARs as they are. The easiest way at the moment is to copy the correct **encryptedappticket** library for your build from `sdk/public/steam/lib/`, and the matching **steamworks4j-encryptedappticket** library from `server/src/main/resources/` to the same folder in your project, then use `SteamEncryptedAppTicket.loadLibraries("path/to/libs")` to load them.

**Comment by ClundXIII** [comment]
@code-disaster for some reason my java refuses to load the library during my jUnit tests:

`testSteamTicketVerifying(com.drakelinglabs.ironarmada.masterserver.MainSteamAuthTest)  Time elapsed: 0.03 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteamworks4j-encryptedappticket64.so: libsdkencryptedappticket.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:114)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:22)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:10)
`

when I run this:
`SteamEncryptedAppTicket.loadLibraries();`

But the libraries exist at the location.

**Comment by ClundXIII** [comment]
Also, it seems that the library does no longer extract the libs anymore. The temporary folder gets created though.
On another note, it would be nice to have some kind of unload function to delete the temporary folder with its contents.

**Comment by code-disaster** [comment]
See my previous comment. By default, the Maven package does not include the **encryptedappticket** libraries anymore. I'm still thinking about how to make this more convenient.

If you build from Source, you can run `mvn [package|install] -Plibs` to create a JAR with all shared libraries included.

**Comment by ClundXIII** [comment]
Ah thx. It worked previously without -Plibs
Also, the jars you linked previously contain the encrypted appticket libraries.

**Comment by ClundXIII** [comment]
OK, I got it working now. Thank you :)

for other people experiencing the same problem:
put the libs into a folder, e.g. lib/ and load them with
SteamEncryptedAppTicket.loadLibraries(Paths.get("").toAbsolutePath() + "/lib/");

My java vm still crashes, but only on exit I think. I will respond to you once I know why this happens.

**Comment by ClundXIII** [comment]
another request @code-disaster 
is there a way to get a native handle from the AppTicket and generate the AppTicket from a native handle?

**Comment by code-disaster** [comment]
What do you mean? There is no native handle, a ticket is just a byte buffer.

**Comment by ClundXIII** [comment]
Well I will need to transfer the ticket somehow: client -> server -> master server.
Do I just take the:
ticketBuffer.asIntBuffer().get(0); and transfer this? or should I transfer
ticketEncrypt.asLongBuffer().get(0); ?
Or is the size variable?

**Comment by AlrikG** [comment]
You have to transform the buffer into an array. Then you can transmitt it via network like this:

// the array which contains the data after copying the data
byte[] steamTickedData;

// get your ticket as buffer
ByteBuffer buffer = getAuthTicket();
if (buffer != null)
{
    // intitialize array
    steamTickedData = new byte[buffer.remaining()];
    // copy data
    buffer.get(steamTickedData);
}

**Comment by code-disaster** [comment]
As @AlrikG said. You can also look at [the example here](https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamEncryptedAppTicketTest.java#L47-L69).

The `ticketSize` output parameter is the size of the ticket in bytes. The ticket data is stored in the first *ticketSize* bytes of the ByteBuffer you provide. Note that steamworks4j does not modify the buffer *state*, so you may want to set `buffer.limit(ticketSize[0])` yourself before passing it on.

**Comment by ClundXIII** [comment]
I am still unable to use the library. Compiling and testing the -server package with the flag works well, all tests pass. When I try to use the jar, I receive the following error:
```
java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteamworks4j-encryptedappticket64.so: libsdkencryptedappticket.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:114)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:22)

```

this is weird, because the libs are extracted even though I specifically tell the library to use a local library folder:
`SteamEncryptedAppTicket.loadLibraries(Paths.get("").toAbsolutePath() + "/lib/");`

**Comment by ClundXIII** [comment]
does libsteamworks4j-encryptedappticket64.so depend on libsdkencryptedappticket.so? Because that might require some extra path exporting to work properly:
LD_LIBRARY_PATH=/home/simon/ironarmada-masterserver/masterserver/lib mvn test -e

however, this gives me another error:
```
java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteamworks4j-encryptedappticket64.so: libsdkencryptedappticket.so: wrong ELF class: ELFCLASS32
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:114)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:22)

```

**Comment by code-disaster** [comment]
Oh the joy! DLL hell meets Valve's messed up file namings. Good catch. No idea yet how I resolve that in a sane way though...

**Comment by code-disaster** [comment]
The most painless solution would be to just drop 32-bit support on Linux. I wonder if anyone would mind...

**Comment by code-disaster** [comment]
@ClundXIII please try with the latest version.

**Comment by code-disaster** [comment]
Small rage-fueled update: shared libraries are a special type of clusterfuck on Linux.

I've been testing on a Linux VM for a few hours, and couldn't get libsdkencryptedappticket.so to load. That is, I can load it just fine, but loading libsteamworks4j-encryptedappticket64.so which depends on libsdkencryptedappticket.so doesn't work - it insists it can't find the goddamn file even if it sits right next to it, and I was able to load it just some nanoseconds ago.

I tried different options, (r)paths, environment variable voodoo ... until ... some Google search result made me look into what they call **soname**. Which is set for libsteam_api.so but not for libsdkencryptedappticket.so. Now the Internet says this shouldn't matter, because it would just take the file name if no soname is set, but of course someone on this party is just lying to my face, because as soon as I add a soname (via **patchelf**), the damn thing loads just fine.

**Comment by ClundXIII** [comment]
Still the same error:
```
java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteamworks4j-encryptedappticket64.so: libsdkencryptedappticket.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:122)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:22)
	at com.drakelinglabs.ironarmada.masterserver.steam.SteamController.<init>(SteamController.java:59)
	at com.drakelinglabs.ironarmada.masterserver.MainSteamAuthTest.testSteamTicketVerifying(MainSteamAuthTest.java:22)
```

Renaming the libsdkencryptedappticket64.so lib to libsdkencryptedappticket.so and loading it via LD_LIBRARY_PATH still works as a workaround.

**Comment by code-disaster** [comment]
> Renaming the libsdkencryptedappticket64.so lib to libsdkencryptedappticket.so and loading it via LD_LIBRARY_PATH still works as a workaround.

I "fixed" this here by installing **patchelf** and run this in `sdk/public/steam/lib/linux64/`:

```patchelf --set-soname libsdkencryptedappticket.so libsdkencryptedappticket.so```

**Comment by ClundXIII** [comment]
Ahhhh I need to upgrade my system in order to install a patchelf version that supports --set-soname. Damn.

Give me a few mins. Apt-get dist-upgrade && pray is in progress.

**Comment by code-disaster** [comment]
Its surprisingly easy to build from [source](https://github.com/NixOS/patchelf):

```
./bootstrap.sh
./configure
make
sudo make install```

**Comment by AlrikG** [comment]
With the latest version my libs cannot be loaded anymore. Until now the .dll files were loaded directly from .jar files.

```
com.codedisaster.steamworks.SteamException: java.io.FileNotFoundException: .\steam_api64.dll (Das System kann die angegebene Datei nicht finden)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:124)
	at com.codedisaster.steamworks.SteamAPI.init(SteamAPI.java:19)
	at net.qb.steamworks.SteamworksState.<init>(SteamworksState.java:28)
	at net.qb.steamworks.SteamworksStateServer.<init>(SteamworksStateServer.java:39)
	at net.qb.steamworks.SteamworkTest.main(SteamworkTest.java:53)
Caused by: java.io.FileNotFoundException: .\steam_api64.dll (Das System kann die angegebene Datei nicht finden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.extractLibrary(SteamSharedLibraryLoader.java:134)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:118)
	... 4 more
com.codedisaster.steamworks.SteamException: java.io.IOException: Failed to read input stream for C:\Users\Alrik\AppData\Local\Temp\steamworks4j\1.7.0-SNAPSHOT\steam_api64.dll
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:124)
	at com.codedisaster.steamworks.SteamGameServerAPI.init(SteamGameServerAPI.java:28)
	at com.codedisaster.steamworks.SteamGameServerAPI.init(SteamGameServerAPI.java:17)
	at net.qb.steamworks.SteamworksStateServer.<init>(SteamworksStateServer.java:54)
	at net.qb.steamworks.SteamworkTest.main(SteamworkTest.java:53)
Caused by: java.io.IOException: Failed to read input stream for C:\Users\Alrik\AppData\Local\Temp\steamworks4j\1.7.0-SNAPSHOT\steam_api64.dll
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.extractLibrary(SteamSharedLibraryLoader.java:160)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.extractLibrary(SteamSharedLibraryLoader.java:129)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:116)
	... 4 more
```

**Comment by ClundXIII** [comment]
Confirmed, same error here:

```
/tmp/steamworks4j/1.7.0-SNAPSHOT/libsteam_api.so: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteam_api.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteam_api.so: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteam_api.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:122)
	at com.codedisaster.steamworks.SteamAPI.init(SteamAPI.java:19)
	at com.codedisaster.steamworks.SteamAPI.init(SteamAPI.java:10)
```

**Comment by Suvitruf** [comment]
Has anyone made `SteamEncryptedAppTicket` works?

With `SteamEncryptedAppTicket.loadLibraries();` I get err:
```
Exception in thread "main" java.lang.NoSuchFieldError: DEBUG
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:15)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:10)
	at com.unnyworld.auth.AuthApp.test(AuthApp.java:46)
	at com.unnyworld.auth.AuthApp.main(AuthApp.java:81)
```

**Comment by code-disaster** [comment]
steamworks4j-server depends on the steamworks4j module, did you update both?

**Comment by Suvitruf** [comment]
```
		<dependency>
			<groupId>com.code-disaster.steamworks4j</groupId>
			<artifactId>steamworks4j</artifactId>
			<version>1.6.2</version>
		</dependency>
```

and I got steamworks4j-server from [here](https://oss.sonatype.org/content/repositories/snapshots/com/code-disaster/steamworks4j/steamworks4j-server/1.7.0-SNAPSHOT/).

**Comment by code-disaster** [comment]
This doesn't work. You'll need both at 1.7.0-SNAPSHOT.

**Comment by Suvitruf** [comment]
Oh, my bad. Thanks. Now I have the problem with `decryptTicket`. Do you have any docs how to use it?
I get err:
```
com.codedisaster.steamworks.SteamException: Direct buffer required.
	at com.codedisaster.steamworks.SteamInterface.checkBuffer(SteamInterface.java:33)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.decryptTicket(SteamEncryptedAppTicket.java:32)
	at com.unnyworld.auth.AuthApp.test(AuthApp.java:72)
	at com.unnyworld.auth.AuthApp.main(AuthApp.java:81)
```

**Comment by code-disaster** [comment]
> I have private key and encrypted string as Hex strings.

What does that mean, exactly?

Have a look at [SteamEncryptedAppTicketTest](https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamEncryptedAppTicketTest.java). For testing, I used the SpaceWar! steam_appid and copied (with a small helper function) their private key from the SDK sample source code to a binary file. This must not be a "hex string", but the binary data, with 32 bytes length exactly.

If you use your own appid, you need to create your private key first on the Steamworks project page.

You don't encode/decode any strings manually. SteamUser.getEncryptedAppTicket() fills the buffer you pass, and also returns the number of bytes written into this buffer. None of the API functions change buffer position/limits, so you [https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamEncryptedAppTicketTest.java#L47-L49](need to set buffer.limit() yourself accordingly).

Same with SteamEncryptedAppTicket.decryptTicket() - you pass the encrypted data, a buffer to be filled with the decrypted data, and the private key. Again, it tells you how much data was written into the buffer, but it [https://github.com/code-disaster/steamworks4j/blob/master/tests/src/main/java/com/codedisaster/steamworks/test/SteamEncryptedAppTicketTest.java#L51-L53](doesn't adjust buffer.limit() by itself).

**Comment by Suvitruf** [comment]
Where can I get secret key with 32 bytes? On Steam https://partner.steamgames.com/apps/sdkauth/ I have just string (btw, it's 64 length long).

**Comment by code-disaster** [comment]
This is just a hex-string version of the 32-byte key. Two characters per byte. A simple conversion could look like this:

```
static byte[] convertKey(String keyAsString) {
	byte[] key = new byte[32];
	for (int b = 0, i = 0; b < 32; b++, i += 2) {
		int n = Integer.parseInt(keyAsString.substring(i, i + 2), 16);
		key[b] = (byte) n;
	}
	return key;
}

// sample key generated in Steamworks interface
byte[] key = convertKey("6c63abde34105dbc5abda34c8dc29b8f2018c3716df30508ec9dbbe88b6b18f1");

```

**Comment by Suvitruf** [comment]
Thanks.
But even in C# sdk I can't decrypt it. 
How can I figure out where the problem? May be I got encrypted ticket that was encrypted with different secret key? Or, I don't know. I get generic error without any info.

If I change steam_appid to 480 like in spacewar Steam demo, and use this key https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserTest.cs#L245, I can decrypt ticket. But when I change steam_appid to my actual app id (and change byte array for my key using your method) it doesn't work )=

**Comment by Suvitruf** [comment]
Hm, if I setup steam_appid with garbage like 11111111111111, encrypt method still working, but decrypt obviously not, like wtf? 

I mean, should we fully publish the game to test decryption?

**Comment by Suvitruf** [comment]
Ok, look like you have to upload at least 1 build of your game to Steam. At least now it works in Unity3d (C#).

With your library I do: 
```
byte[] privateKey = convertKey("my_private_key");
byte[] steamTickedData = {}; // byte array of encrypted ticket

ByteBuffer ticketEncrypt = ByteBuffer.allocateDirect(steamTickedData.length).order(ByteOrder.nativeOrder());
ByteBuffer ticketDecrypt = ByteBuffer.allocateDirect(1024);
ticketEncrypt.clear();
ticketDecrypt.clear();

ticketEncrypt.put(steamTickedData);
ticketEncrypt.flip();

int[] size = new int[1];

	
SteamEncryptedAppTicket lib = new SteamEncryptedAppTicket();	


try {
	if (lib.decryptTicket(ticketEncrypt, ticketDecrypt, privateKey, size)) {
		System.out.println("decrypted app ticket size: " + size[0]);
		ticketDecrypt.limit(size[0]);

		ByteBuffer dataIncluded = ByteBuffer.allocateDirect(100);
		int dataLength = lib.getUserVariableData(ticketDecrypt, dataIncluded);
		if (dataLength > 0) {
			dataIncluded.limit(dataLength);
			byte[] userData = new byte[dataLength];
			dataIncluded.get(userData);
			String userString = new String(userData);
			System.out.println("included user data: " + dataLength + " bytes, '" + userString + "'");
		}

	}
	else {
		System.err.println("failed to decrypt app ticket");
	}
}
catch (SteamException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}

And finally I see something in logs:

`
decrypted app ticket size: 102
included user data: 4 bytes, 'DT  '
`

Is it ok? Or, did I miss something?

**Comment by Suvitruf** [comment]
Ohm again, my bad. It's int value that I've encrypted. So, everything is ok.

But, to summarize:
1) You have to upload at least one build to Steam.
2) You need to make few things with .jar's. I mean, I use 1.7.0 versions of .jars, and they have needed lins inside. But I couldn't make it works from the box. 
It works only if I load libs like `SteamEncryptedAppTicket.loadLibraries(Paths.get("").toAbsolutePath() + "/libs/");` and copy sdkencryptedappticket64.dll and steamworks4j-encryptedappticket64.dll to this libs folder. Otherwise i get error:
`java.lang.UnsatisfiedLinkError: com.codedisaster.steamworks.SteamEncryptedAppTicketNative.decryptTicket(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II[BI[I)Z`

**Comment by Suvitruf** [comment]
Oh, it works in Eclipse.

But doesn't work when I'm running built .jar. Get error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.7.0-SNAPSHOT/libsteamworks4j-encryptedappticket.so: libsdkencryptedappticket.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:124)
	at com.codedisaster.steamworks.SteamEncryptedAppTicket.loadLibraries(SteamEncryptedAppTicket.java:22)
	at com.unnyworld.auth.AuthApp.main(AuthApp.java:55)
```

**Comment by code-disaster** [comment]
There are a few open issues. Some of those I'm not yet happy with right now:

- The steamencryptedappticket libraries are not part of the redistributable package, so I'm reluctant to distribute them in release builds of **steamworks4j-server**. To build a Maven package which includes all libraries, you need to build them yourself right now, e.g. with `mvn install -pl server -Plibs`. If the `libs` profile is active, the libraries are copied from the `./sdk` folder. This is activated by default for the `java-wrapper` module, thats why the redistributables are included in the **steamworks4j** package.

- As noted in a [previous comment](#issuecomment-302893307), I had trouble with loading libsdkencryptedappticket.so on Linux myself, until I "patched" my copy with patchelf to add a soname. If someone with a better understanding of shared library hell on Linux can show me a better way, I would be happy to listen.

**Comment by Suvitruf** [comment]
`patchelf --set-soname libsdkencryptedappticket.so libsdkencryptedappticket.so` in **sdk/public/steam/lib/linux64** gives me error: 
`stat: No such file or directory`

**Comment by code-disaster** [comment]
I'm closing this now. If you still experience issues with the 1.7.0 release, please open a new ticket.

I've also written down a description of the libsdkencryptedappticket/soname workaround on Linux here: [link](http://code-disaster.github.io/steamworks4j/known-issues.html)
