### ISSUE TITLE
SteamApps BIsDlcInstalled

### ISSUE THREAD

**Issue by kevinmurphy678** [code-disaster/steamworks4j#50]
SteamApps is currently missing some functions relating to checking if DLC is installed. I need access to

virtual bool BIsDlcInstalled( AppId_t appID ) = 0;

It would be helpful if this was added. Thanks

**Comment by AlrikG** [comment]
As a workaround you can use SteamGameServer.userHasLicenseForApp(SteamID steamID, int appID) to check if an user has the desired DLC
