### ISSUE TITLE
Steam isDlcInstalled not in the latest release

### ISSUE THREAD

**Issue by lsliwko** [code-disaster/steamworks4j#57]
Hello,

I have seen you added a method isDlcInstalled in SteamApps object, but current release (v1.6.2) doesn't have this method yet.

Would you mind releasing current build so we can use this function?

Also, will it be possible to add function to retrieve steamworks4j library version?
We can use that for debugging purposes.

Thank you very much!

Les

**Comment by code-disaster** [comment]
I plan to release 1.7.0 shortly, for now 1.7.0-SNAPSHOT is available at https://oss.sonatype.org/content/repositories/snapshots
