### ISSUE TITLE
Downloading a published file via fileRead has stopped working

### ISSUE THREAD

**Issue by Zarkonnen** [code-disaster/steamworks4j#61]
Previously, I was able to download a published file by name using the following code:

	public static byte[] readFile(String name) throws SteamException {
		int sz = storage.getFileSize(name);
		ByteBuffer bb = ByteBuffer.allocateDirect(sz);
		storage.fileRead(name, bb, sz);
		byte[] a = new byte[sz];
		bb.get(a);
		return a;
	}

Now, storage.getFileSize returns 0.

**Comment by code-disaster** [comment]
Did you manage to resolve that issue?

**Comment by Zarkonnen** [comment]
OK, so the problem seems to be with Steam, in that the files aren't locally available, rather than with steamworks4j. See [this post on the Steamworks forum](http://steamcommunity.com/groups/steamworks/discussions/9/1621726179585571985/) for the ongoing saga.
