### ISSUE TITLE
How do I get the ticket token.

### ISSUE THREAD

**Issue by id4alex** [code-disaster/steamworks4j#63]
Hi Guys,

I couldn't find how to get the ticket token using steamworks4j.  Here is my snippet.
`try {
            SteamUser steamUser = new SteamUser(userCallback);
            System.out.println(steamUser.getSteamID());

            ByteBuffer userAuthTicketData = ByteBuffer.allocateDirect(256);
            int[] sizeRequired = new int[1];
            SteamAuthTicket userAuthTicket = steamUser.getAuthSessionTicket(userAuthTicketData, sizeRequired);
            System.out.println(userAuthTicket.isValid()); //true
            
        } catch (SteamException e) {
        }`

Could anyone give some tips? Thanks in advanced!

**Comment by AlrikG** [comment]
Hi, 
hm I don't get it what you are trying to do. You already get the SteamAuthTicket. That is all you need

**Comment by id4alex** [comment]
@AlrikG  it's going like this, I want to query some data from pubg server, but it requires auth ticket when requesting via websocket.

> 

How to get ticket (aka access token aka password?):

Run wireshark, filter by: tcp.port == 81 && http

Run game and wait for loading menu (lobby)

Looking for something like "/userproxy?provider=steam&.." in wireshark and open it (by left click)

Copy Value from middle frame, it's must be more 450 symbols (468 for me)

You can found full lenght ticket in "Request URI Query Parameter",press right mouse -> copy -> value and remove "ticket="

Ticket will dead after few minutes in offline (sure, maybe ip change need to regenerate token). OR it maybe works while you in game.


This is how to get the ticket via greenworks.

> var greenworks = require('greenworks'); // Tested with greenworks-0.10.0
if (!greenworks.initAPI()) {
  console.log('An error occured initializing Steam API.');
  process.exit(1);
}

function getKey(cb){
  greenworks.getAuthSessionTicket(function(a,b){
    if(a.ticket){
      const ticket = a.ticket.toString('hex');
      cb(null, ticket.toUpperCase());
    }
  }, function(error){
    cb(error, false);
  });
}


getKey((error, token) => {
  if(err) return console.log(`Error:   ${error}`);
  console.log(`Auth token is ${token}`);
});


and I think it should be ok to get the ticket via steamworks4j, so here comes the question, do you guys have any ideas?
