### ISSUE TITLE
SteamUGC deleteItem() not implemented

### ISSUE THREAD

**Issue by Shadow6390** [code-disaster/steamworks4j#64]
Greetings,

I am currently developing Steam Workshop support for an application and during item creation and submission, the process can fail due several reasons. As stated on the Steamworks SDK, there is no way of canceling the process once it's done. As such, temporary junk file appear on the user's workshop due to the error caused.

One solution I found to fix this is to call DeleteItem after an unsuccessful submission. However, the SteamUGC does not seem to implement this method call. Is this intended?

Best Regards,
Diogo Braga

**Comment by AlrikG** [comment]
No, this is a new command which was released with Steamworks SDK 1.41. So this need to be implemented.

**Comment by Shadow6390** [comment]
Hey AlrikG,

Thank you for letting me know. I'll try to validate the call's validation state before submitting it and, if all else fails, just let the users know it's a known issue! :smile:

**Comment by AlrikG** [comment]
Hey @Shadow6390,
I added deleteItem(). You can use my PR or just wait until @code-disaster has merged it into the master branch.

**Comment by Shadow6390** [comment]
Hey AlrikG,

Thank you for the implementation! It sure comes in handy! :smiley:
