### ISSUE TITLE
Support for SteamFriends.getFriendGamePlayed() ??

### ISSUE THREAD

**Issue by wcomohundro** [code-disaster/steamworks4j#68]
Any chance of someone adding in support for SteamFriends.getFriendGamePlayed() ?
Support for this function would help with a matchmaking process that is restricted to FriendOnly lobbies.
The java code is rather trivial, but I am afraid the native code/library rebuild is beyond me.

**Comment by code-disaster** [comment]
Added. Let me know if you run into any issues.
