### ISSUE TITLE
steam workshop process

### ISSUE THREAD

**Issue by titoasty** [code-disaster/steamworks4j#7]
Hi,

I'm trying to use steam workshop and I'm facing some issues.
As function names are different, I can't figure how to simply publish a file on workshop.
I tried publishWorkshopFile but I always have "fileNotFound". Same for fileWrite or fileShare...

**Comment by code-disaster** [comment]
How are function names different? I tried to not change naming, except to adjust to common Java camelCase conventions, and to get rid of the awful Hungarian notation.

Do you get any error messages? Our publishing workflow with the Halfway editor is:

- Write both the file, and its preview image, using the RemoteStorage.fileWriteStream*() API
- If the file hasn't been published before:
  - Call RemoteStorage.fileShare() with workshop item, wait for callback
  - Call RemoteStorage.fileShare() again with preview image, wait for callback
  - Call RemoteStorage.publishWorkshopFile(), wait for callback
    - If needsToAcceptWLA flag is set, open overlay with URL "http://steamcommunity.com/sharedfiles/workshoplegalagreement", then stop
    - If needsToAcceptWLA is not set, open overlay with URL "http://steamcommunity.com/sharedfiles/filedetails/?id=" + publishedFileID.id (we publish files with visibility set to private, so the creator needs to set them public on the Steam webpage)
- If the file has been published before:
  - Use the PublishedFileUpdate API to update the workshop item

**Comment by titoasty** [comment]
ok this is exactly what I did according to the example provided.
so the problem may come from my workshop config because every time I call fileShare() on the file I wrote, I have a "FileNotFound" result...

**Comment by code-disaster** [comment]
Yes, a FileNotFound error on fileShare() is odd. You could try to enumerate and read your files again using the RemoteStorage file API, just to check if the writes really worked.

**Comment by titoasty** [comment]
Yes I already tried to check file existence with fileExists and by listing
files, but nothing..
The weird thing is that I have no error when I'm writing the file..
Perhaps a problem of context? I'm testing directly from eclipse, with a
steam client launched, I checked workshop config on steam but still
nothing... (and steam doc/help is not very useful actually)

**Comment by code-disaster** [comment]
I think you don't even touch the workshop part yet. Did you configure your Steam Cloud settings (quota per user, # of files allowed) in Steamworks?

**Comment by titoasty** [comment]
Yes I set 10 files per user and 1024bytes.

**Comment by code-disaster** [comment]
I hope that's a typo. 1024 bytes ain't much! ;)

**Comment by titoasty** [comment]
You know what ? I was assuming it was kbytes instead of bytes (and fully working now ! wow thanks !).
So you probably are a genius :dancer: 

But anyway, this is quite disturbing that when the remote storage is full there is no error returned, only a "fileNotFound" but no error while writing the file.
So it's probably a steam issue ?

**Comment by titoasty** [comment]
now I tried using the provided SteamAPITestApplication to publish files.
everything works correctly, using my app_id.
BUT, when I try "ugc query", it always returns me nothing... any idea ? (I can see the files on my workshop though)
