### ISSUE TITLE
Is it possible to use this library with SteamCMD instead of the standard Steam Client?

### ISSUE THREAD

**Issue by XaeroDegreaz** [code-disaster/steamworks4j#71]
From [the docs](https://developer.valvesoftware.com/wiki/SteamCMD#With_a_Steam_account)

> The Steam Console Client or SteamCMD is a command-line version of the Steam client. 

I have SteamCMD running, and have logged in via the console. I started up some of the steam tests, but they all fail with

```
[S_API FAIL] SteamAPI_Init() failed; ipcserver GetSteamPath failed.
[S_API FAIL] SteamAPI_Init() failed
  Steam API initialized: false
  Steam client active: false
```
The tests run just fine when running the standard Steam client.

What are the specific things that `steamworks4j` is looking for to determine whether or not a Steam client is running (running processes, listening ports, etc)? Is SteamCMD simply unable to provide that functionality so that it's observable as a standard client?

I'd like to write a wrapper around some of the Steamworks APIs (specifically matchmaking lobbies) that runs on dedicated headless hardware in the cloud. The problem is that I don't want to install a full Steam installation on that hardware for this proxy application. I was hoping that I could get away with using SteamCMD instead :)

**Comment by code-disaster** [comment]
I'm afraid I can't help you with that. The only context I've ever used SteamCMD in is to run build uploads via SteamPipe.

> What are the specific things that steamworks4j is looking for to determine whether or not a Steam client is running (running processes, listening ports, etc)?

The Java wrapper doesn't do anything in this regard - it just loads the native DLL and forwards API calls.
