### ISSUE TITLE
No implementation for get/set LobbyMemberData

### ISSUE THREAD

**Issue by XaeroDegreaz** [code-disaster/steamworks4j#72]
I see an implementation for `setLobbyData` and `getLobbyData`, but there is no implementation for getting, or setting data for a member of a lobby in the matchmaking implementation.

Docs: https://partner.steamgames.com/doc/api/ISteamMatchmaking#SetLobbyMemberData

Edit: After reading more of your documentation on how to build and make new additions to the API, I think I may have figured out the process and am in the middle of making new calls. I'll let you know if I simply can't get it to work.

**Comment by code-disaster** [comment]
Merged in #73.
