### ISSUE TITLE
UnsatisfiedLinkError ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by mibollma** [code-disaster/steamworks4j#77]
Trying to use the library within a **openjdk:8-jdk-alpine** docker container leads to the following error when calling `SteamEncryptedAppTicket.loadLibraries`:

`nested exception is java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.8.0/libsdkencryptedappticket.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/steamworks4j/1.8.0/libsdkencryptedappticket.so)`

Any ideas how to fix that?

**Comment by code-disaster** [comment]
I have no experience using Docker containers. Maybe some dependency missing? For example, here on WSL (Ubuntu on Windows), there's a `/lib64/ld-linux-x86-64.so.2` which is a symbolic link to `/lib/x86_64-linux-gnu/ld-2.27.so`.

Also, no idea if it's related, but there's some [known issue](http://code-disaster.github.io/steamworks4j/known-issues.html) with libsdkencryptedappticket.so - maybe worth a look too.

**Comment by httpdigest** [comment]
Alpine uses [musl](https://www.musl-libc.org/) as standard C library implementation, and not glibc (the one using ld-linux-x86-64.so.2). The SteamWorks natives must be recompiled for musl (preferably under Alpine) to work under Alpine Linux. Your best workaround would be to just use a glibc-based Linux distribution, such as Debian or Ubuntu as base image, such as openjdk:8-jdk-slim.

**Comment by mibollma** [comment]
Thanks for the explanation. It's correct
