### ISSUE TITLE
If there be a posibility that we not to use steam_appid.txt, but use another way to inform the steamworks?

### ISSUE THREAD

**Issue by XenoAmess** [code-disaster/steamworks4j#80]
well sometimes it is really awful when dealing with steam_appid.txt.
It will save a lot of trouble if we be able to hardcode it somewhere but not save it in steam_appid.txt.
I know steam_appid.txt is needed for steamworks, but if there be some possibility that we do some tricks here, like generate the file just before steamworks start, then delete the file when finished?

**Comment by AlrikG** [comment]
Why is it awful? Just don't deploy it with your game/application. 

What I do:
steam_appid.txt is included in my repo but it is not in the output folder generated by the build script. So there is no problem for me. You only have to test the "SteamAPI.restartAppIfNecessary()" feature once. For this single case you have to remove the steam_appid file temporary.

**Comment by XenoAmess** [comment]
@AlrikG Then try develop 2 games and 1 engine at the same time and you will know how awful it can be.
And don't forget if you want to make your consumer be able to move the game folder in other places(like into there USB flash disk / tf card), steam_appid will still be a necessary.

**Comment by AlrikG** [comment]
Okay I didn't knew your use case. Maybe could do this:
Your engine doesn't require the steam_appid.txt. Every game has its own steam_appid.txt. Deploy your games without these files and create a "portable launcher". 
This launcher will then be called by the user (on USB stick) without any parameter. If this happens, you generate the steam_appid.txt by your launcher code. But if the user wants to play the game via Steam UI, you also call your "portable launcher" but with parameters. The parameters prevents that the steam_appid.txt file will be created.

**Comment by XenoAmess** [comment]
@AlrikG that sounds like a good solution... I will try it. 
Thx.
