### ISSUE TITLE
Player Name

### ISSUE THREAD

**Issue by haubna** [code-disaster/steamworks4j#82]
Would it be possible to add https://partner.steamgames.com/doc/api/ISteamFriends#GetPlayerNickname
It retrieves the nickname of a Steam user which is very handy when you use the workshop.

**Comment by code-disaster** [comment]
Are you sure that's the function you are looking for? It gets the nickname _you_ can set for users in your friends list. (I use it to remind myself who the hell the persons are behind those cryptic (and sometimes changing) Steam user names)

**Comment by haubna** [comment]
Oh ok nervmind then. I haven't found a proper function to retrieve the
username from a OwnerID. getFriendPersonaName obviously returns Unknown
when the user isn't in your friends list. Do you know the proper function?

Daniel Ludwig <notifications@github.com> schrieb am Mi. 17. Juli 2019 um
11:36:

**Comment by code-disaster** [comment]
That's a good question. I'm not aware of any.

**Comment by haubna** [comment]
That's odd. You only get the OwnerID when retrieving workshop objects.

Daniel Ludwig <notifications@github.com> schrieb am Mi. 17. Juli 2019 um
11:53:

**Comment by andy98725** [comment]
In my limited testing, getFriendPersonaName seems to return the Username of a userID even when the user isn't in your friends list. Seems like quite the misnomer; regardless, it should work for getting player names.
