### ISSUE TITLE
No callback for GetAuthSessionTicketResponse

### ISSUE THREAD

**Issue by tylerhasman** [code-disaster/steamworks4j#83]
I don't see any callback for this. It should be in SteamUserCallback.

https://partner.steamgames.com/doc/api/ISteamUser#GetAuthSessionTicketResponse_t

**Comment by code-disaster** [comment]
Added. Please let me know if you run into any issues.

**Comment by tylerhasman** [comment]
Thank you! I will try this out and let you know if it works.

**Comment by tylerhasman** [comment]
It works but is there any way you could compile it for OSX as well?

**Comment by code-disaster** [comment]
Yeah, if I can figure out the mess that is building on OS X Catalina.

**Comment by tylerhasman** [comment]
Awesome, thank you so much

**Comment by tylerhasman** [comment]
Hey everything works great now, could you publish this version to your maven repo now?

**Comment by nhouser9** [comment]
I know this thread is two years old but I don't know where else to comment. I spent a day trying to figure out what was wrong with my code only to eventually find that the version hosted on maven does not include this fix. Where can I find a version that incorporates this fix? How can I use it? @tylerhasman @code-disaster
