### ISSUE TITLE
Achievements only run when app closes

### ISSUE THREAD

**Issue by kennycason** [code-disaster/steamworks4j#88]
I'm trying to make it so that achievements pop up as a player unlocks them. Currently the achievements only pop up once the game is closed. Is this possible?

Thanks for the library, it's been very easy to get running.

**Comment by cairn4** [comment]
I've been working on setting up achievements in my libgdx game, and was noticing the same behavior.  Then I realized that I'm not actually able to bring up the SteamOverlay while the game is running via Android Studio (but it does work when running the game from the Steam client) - might be related to the achievement notifications not showing up?

**Comment by LobbyDivinus** [comment]
I experienced the same issue and was able to solve it by using 
```java
steamUserStats.storeStats();```

**Comment by Superwutz** [comment]
I had the same problam and can confirm, that @LobbyDivinus soloution is working!

**Comment by kennycason** [comment]
@LobbyDivinus @Superwutz thanks a lot for the response + confirmation. I'll give it a shot!

**Comment by code-disaster** [comment]
Yes, without calling storeStats() the Steam client just caches your achievement updates, and triggers all popups on exit.
