### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by JSmith-LDG** [code-disaster/steamworks4j#93]
Getting java.lang.UnsatisfiedLinkError: /tmp/steamworks4j/1.8.0/libsteamworks4j.so: /tmp/steamworks4j/1.8.0/libsteamworks4j.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch) on ubuntu 18.04

**Comment by code-disaster** [comment]
The error message indicates that you are trying to run on a 32-bit Linux system, which has been removed with version 1.7.0.
