### ISSUE TITLE
IndicateAchievementProcess not working

### ISSUE THREAD

**Issue by Superwutz** [code-disaster/steamworks4j#98]
Hi guys,

I am trying to bring up a popup indicating achievement process.
I made a little function for it:

```java
	public boolean indicateProgress(String name) {
		int curProgress=0;
		int maxProgress=0;
		boolean result = stats.indicateAchievementProgress(name, curProgress, maxProgress);
		System.out.println("Indicating progress for "+name+" ("+curProgress+"/"+maxProgress+")");
		return result;
	}
```
Both curProgress and maxProgress stay at zero and also the popup does not fire..

**Comment by code-disaster** [comment]
I think you misunderstood the purpose of this function. You are supposed to provide these parameters, so you need to calculate them by yourself, using your game's values and what you receive from the achievement/stats callbacks.

Also, as far as I remember you may need to call storeStats() right after that to trigger the Steam overlay popup.

**Comment by Superwutz** [comment]
Ah lol in that case I really misunderstood it. I am going to try it out!
